# Question1


In [1]:
for x in range (2000,3200):
print(x)

IndentationError: expected an indented block (<ipython-input-1-58177a33d7d0>, line 2)

# Question 2

In [2]:
print("donner number",num):
factorial = 1
if num < 0:
   print("Sorry")
elif num == 0:
   print("The factorial of 0 is 1")
elif:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

SyntaxError: invalid syntax (<ipython-input-2-e502a81cfb15>, line 1)

# Question3

In [4]:

d = dict()

for x in range(1,n+1):
    d[x]=x*x

print(d) 


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# Question4


In [5]:
print(missing_char)
for i in (missing_char):
print (missing_char.remove(i))
print(x)

IndentationError: expected an indented block (<ipython-input-5-14f123f4d7d9>, line 3)

# Question5

In [6]:
import numpy as np
x = np.array([[0,1],[2,3],[4,5]])
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# Question6 

In [7]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("array1:")
print(x)
print("array2:")
print(y)
print("Covariance matrix",np.cov(x, y))

array1:
[0 1 2]
array2:
[2 1 0]
Covariance matrix [[ 1. -1.]
 [-1.  1.]]


# Question7

In [8]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

Provide D: 100,150,180
[18, 22, 24]
